db.restaurants.find().pretty()
db.restaurants.find({},{"restaurant_id":1,"name":1,"borough":1,"cuisine":1}).pretty()
db.restaurants.find({},{"_id":0,"restaurant_id":1,"name":1,"borough":1,"cuisine":1}).pretty()
db.restaurants.find({},{"_id":0,"restaurant_id":1,"name":1,"borough":1,"address.zipcode":1}).pretty()
db.restaurants.find({borough:"Bronx"}).pretty()
db.restaurants.find({borough:"Bronx"},{name:1}).limit(5).pretty()
db.restaurants.find({borough:"Bronx"},{name:1}).skip(5).limit(5).pretty()
db.restaurants.find({"grades.score":{$gt:90}},{name:1,"grades.date":1,"grades.grade":1,"grades.score":1}).pretty()
db.restaurants.find({$and:[{"grades.score":{$gt:80}},{"grades.score":{$not:{$gt:100}}}]},{name:1,"grades.date":1,"grades.grade":1,"grades.score":1}).pretty()
db.restaurants.find({"address.coord":{$lt:-95.754168}},{name:1,"address.coord":1}).pretty()
db.restaurants.find({$and:[{cuisine:{$ne:"American "}},{"grades.score":{$gt:70}},{"address.coord":{$lt:-65.754168}}]},{name:1,cuisine:1,"grades.date":1,"grades.grade":1,"grades.score":1,"address.coord":1}).pretty()
db.restaurants.find({cuisine:{$ne:"American "},"grades.score":{$gt:70},"address.coord":{$lt:-65.754168}},{name:1,cuisine:1,"grades.date":1,"grades.grade":1,"grades.score":1,"address.coord":1}).pretty()
db.restaurants.find({cuisine:{$ne:"American "},"grades.grade":"A",borough:{$ne:"Brooklyn"}},{name:1,cuisine:1,borough:1,"grades.date":1,"grades.grade":1}).sort({cuisine:-1}).pretty()
db.restaurants.find({name:/^Wil/},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurants.find({name:/ces$/},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurants.find({name:/Reg/},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurants.find({$and:[{borough:"Bronx"},{$or:[{cuisine:"American "},{cuisine:"Chinese"}]}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurants.find({$or:[{borough:"Staten Island"},{borough:"Queens"},{borough:"Bronx"},{borough:"Brooklyn"}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurants.find({$and:[{borough:{$ne:"Staten Island"}},{borough:{$ne:"Queens"}},{borough:{$ne:"Bronx"}},{borough:{$ne:"Brooklyn"}}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurants.find({"grades.score":{$lt:10}},{restaurant_id:1,name:1,borough:1,cuisine:1,"grades.score":1}).pretty()
db.restaurants.find({$and:[{cuisine:/seafood/},{cuisine:{$not:/American/}},{cuisine:{$not:/Chinese/}},{name:{$not:/^Wil/}}]},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurants.find({$and:[{"grades.grade":"A"},{"grades.score":11},{"grades.date":"2014-08-11T00:00:00Z"}]},{restaurant_id:1,name:1,"grades.date":1,"grades.grade":1,"grades.date":1}).pretty()
db.restaurants.find({$and:[{"grades.grade.1":"A"},{"grades.score":9},{"grades.date":"2014-08-11T00:00:00Z"}]},{restaurant_id:1,name:1,"grades.date":1,"grades.grade":1,"grades.date":1}).pretty()
db.restaurants.find({$and:[{"address.coord.1":{$gt:42}},{"address.coord.1":{$not:{$gt:52}}}]},{restaurant_id:1,name:1,address:1}).pretty()
db.restaurants.find({}).sort({name:1}).pretty()
db.restaurants.find({}).sort({name:-1}).pretty()
db.restaurants.find({}).sort({cuisine:1,borough:-1}).pretty()
db.restaurants.find({"address.street":{$exists:true}}).pretty()
db.restaurants.find({coord:/^^.^^/},{name:1,borough:1,coord:1,cuisine:1}).pretty()
db.restaurants.find({"grades.score":{$mod:[7,0]}})
db.restaurants.find({name:/mon/},{name:1,borough:1,coord:1,cuisine:1}).pretty()
db.restaurants.find({name:/^Mad/},{name:1,borough:1,coord:1,cuisine:1}).pretty()